FieldOfDreams/FieldOfDreams/Controllers/MatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Services.Interfaces;
using Common.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FieldOfDreams.Controllers
{
    public class MatchController : Controller
    {
        private readonly IMatchService matchService;
        private readonly IWordService wordService;
        public MatchController(IMatchService matchService, IWordService wordService)
        {
            this.matchService = matchService;
            this.wordService = wordService;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var matches = matchService.GetAllMatches();
            return View(matches);
        }

        [Authorize(Roles = "User")]
        public IActionResult GetCurrentUserMatches() 
        {
            var matches = matchService.GetCurrentUserMatches();
            return View(matches);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult GetUsersWithPoints() 
        {
            var usersWithPoints = matchService.GetUsersWithPoints();
            return View(usersWithPoints);
        }

        [Authorize(Roles = "User")]
        public IActionResult GetGameView()
        {
            Random rnd = new Random();
            var word = wordService.GetAll().ToList();
            var model = new MatchViewModel();
            if (word.Any())
            {
                int r = rnd.Next(word.Count());
                model.Question = word[r].Question;
                model.WordId = word[r].Id;
                model.Answer = word[r].Answer;
                return View(model);
            }

            return View("NoGame");
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public async Task<IActionResult> WishWord(MatchViewModel model)
        {
            var isWon = await matchService.WishWord(model);
            if (isWon)
            {
                return Json(new { isWon, message="Вы угадали!"});
            }
            else
            {
                return Json(new { isWon, message = "Вы проиграли!" });
            }
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public async Task<IActionResult> WishLetter(MatchViewModel model, int? wordId)
        {
            var isNumeric = char.IsDigit(model.UserAnswerChar);
            var initialWord = matchService.PrepareWord(model);
            if (!isNumeric && !(model.TryCount > model.Answer.Length - 2))
            {
                if (!model.Answer.Contains(model.UserAnswerChar))
                {
                    return Json(new { isWon = false, message = "Не правильно! У вас осталось несколько попыток", isFinish = false, word = initialWord });
                }

                var word = matchService.WishLetter(model, initialWord);
                if (!word.Contains("*"))
                {
                    await matchService.SaveMatchSession(model, true, word, (int)wordId);
                    return Json(new { isWon = true, message = "Вы выиграли!", isFinish = true, word });
                }

                return Json(new {isWon = true, word, answerbuff = model.UserAnswerBuff, message = "Вы отгадали! продолжайте...", isFinish = false });
            }

            await matchService.SaveMatchSession(model, false, model.UserAnswerBuff, (int)wordId);
            return Json(new { isWon = false, message = "Вы проиграли!", isFinish = false });
        }
    }
}

FieldOfDreams/FieldOfDreams/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Services.Interfaces;
using Castle.Core.Internal;
using Common.Models;
using Domain.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FieldOfDreams.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly IUserService userService;
        public UsersController(IUserService userService)
        {
            this.userService = userService;
        }

        public IActionResult Index()
        {
            return View(userService.GetUsers());
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id.IsNullOrEmpty())
            {
                return NotFound();
            }

            var user = await userService.GetUserAsync(id);
            return View(user);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (id.IsNullOrEmpty())
            {
                return NotFound();
            }

            var user = await userService.GetUserAsync(id);
            var model = new UserCreateEditModel()
            {
                Email = user.Email, UserName = user.UserName, Phone = user.PhoneNumber
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserCreateEditModel model)
        {
            if (ModelState.IsValid)
            {
                await userService.EditUserAsync(model);
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id.IsNullOrEmpty())
            {
                return NotFound();
            }

            await userService.DeleteUserAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

FieldOfDreams/FieldOfDreams/Controllers/WordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Services.Interfaces;
using Castle.Core.Internal;
using Common.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FieldOfDreams.Controllers
{
    [Authorize(Roles = "Admin")]
    public class WordController : Controller
    {
        private readonly IWordService wordService;
        private readonly IUserService userService;
        public WordController(IWordService wordService, IUserService userService)
        {
            this.wordService = wordService;
            this.userService = userService;
        }
        public IActionResult Index()
        {
            var words = wordService.GetAll();
            return View(words);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }

            var word = await wordService.GetWordAsync((int)id);
            return View(word);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var word = await wordService.GetWordAsync((int)id);
            var model = new WordCreateEditModel()
            {
                Answer = word.Answer,
                Question = word.Question,
                CreatorId = word.CreatorId
            };

            ViewBag.Users = new SelectList(userService.GetUsers(), "Id", "Email");

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(WordCreateEditModel model)
        {
            if (ModelState.IsValid)
            {
                await wordService.EditWordAsync(model);
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await wordService.DeleteWordAsync((int)id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(WordCreateEditModel model)
        {
            if (ModelState.IsValid)
            {
                await wordService.CreateWordAsync(model);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }
    }
}

FieldOfDreams/FieldOfDreams/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FieldOfDreams</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FieldOfDreams</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users list</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Word" asp-action="Index">Words list</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Match" asp-action="Index">Matches list</a>
                            </li>
                        }
                        else if(User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Match" asp-action="GetGameView">Play game</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Match" asp-action="GetCurrentUserMatches">Match history</a>
                            </li>
                        }
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - FieldOfDreams - 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>